Repository AGF-Equipamentos/agf-bi, pull requests merged in 2021-07, with the labels that each got.

#4 fix: removing localStorage setItem from ops request
  .env.example
  src/hooks/auth.tsx
Labels: agf-bi, bug

#9 fix: replacing power bi links to env variables
  src/pages/Imports/index.tsx
  src/pages/Productivity/index.tsx
  src/pages/Revenues/index.tsx
Labels: agf-bi, help wanted

#14 refactor: add MTl20, MTL12 and BH07S working hours
  src/pages/ProductivityProduction/index.tsx
Labels: agf-bi, enhancement

#17 Refactor/ improving quering storages
  src/components/Loader/index.tsx
  src/hooks/auth.tsx
  src/hooks/useFetch.tsx
  src/pages/ProductivityProduction/index.tsx
Labels: agf-bi, enhancement

#15 feat: add products array in the query param
  src/pages/ProductivityProduction/index.tsx
Labels: agf-bi, enhancement

#18 feat: improving ops query
  src/pages/ProductivityProduction/index.tsx
Labels: agf-bi, enhancement
